---
title: "Coronavírus - VIZ"
author: "Giovani de Almeida Valdrighi"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```


```{r, include = FALSE}
#necessary packages
library(crosstalk)
library(plotly)
library(ggplot2)
library(sf)
library(geobr)
library(dplyr)
library(gapminder)
```

```{r}
#handling the dataframe
data_coronavirus_brasil <- read.csv("arquivo_coronavirus.csv", sep = ";") 
data_coronavirus_brasil$data <- as.Date(data_coronavirus_brasil$data, format = "%d/%m/%Y")
temp <- data_coronavirus_brasil  %>%
  filter(municipio != "") %>%
  filter(populacaoTCU2019 != "") %>%
  select(municipio, estado, data, semanaEpi, populacaoTCU2019, 
         casosAcumulado, casosNovos, obitosAcumulado, obitosNovos) %>%
  mutate(cidade_grande = ifelse(as.numeric(populacaoTCU2019) > 500000, "grandes", "pequenas")) %>%
  group_by(estado, cidade_grande, data) %>%
  summarise(casosNovos = sum(casosNovos),
            populacao = mean(as.numeric(populacaoTCU2019)))


#calculating moving average
temp$mov_avg <- 0
moving_avg <- function(vec, n = 7){
  return(stats::filter(vec, rep(1 / n, n), sides = 2))
}
for(j in unique(temp$estado)){
  for(i in c("pequenas", "grandes")){
    if(NROW(temp[(temp$cidade_grande == i) & (temp$estado == j), "casosNovos"]) == 0){
      temp[(temp$cidade_grande == i) & (temp$estado == j), "mov_avg"] = 0.
    }else{
      temp[(temp$cidade_grande == i) & (temp$estado == j), "mov_avg"] = moving_avg(temp[(temp$cidade_grande == i) & (temp$estado == j), "casosNovos"])
    }
  }
}

#setting plot information
title <- "Casos diários no estado de São Paulo agrupados\npelo tamanho das cidades (pop.)"
x_lab <- "Data"
y_lab <- "Número de casos"
y_ticks <- seq(0, 7000, 1000)
color_title <- "Cidades"
color_lab <- c("pequenas", "grandes")
color_val <- c("#F26457", "#1D6A73")


plot <- ggplot(temp %>% filter(estado == "SP")) +
  geom_area(aes(x = data, y = mov_avg, fill = cidade_grande), position = position_stack(reverse = TRUE)) +
  scale_x_date(x_lab, date_breaks = "2 week", date_labels = "%d/%m") +
  scale_y_continuous(y_lab, breaks =y_ticks) +
  scale_colour_manual(color_title, values = color_val, aesthetics = "fill") +
  ggtitle(title) +
  theme(legend.position = "bottom")
ggplot <- ggplotly(plot) %>% 
  layout(legend = list(orientation = "h", 
                       x = 0.3, 
                       y =- 0.25,
                       title = list(text = "Cidades \t")))
plot
```
```{r}
ggplot(temp %>% filter(estado == "AM")) +
  geom_area(aes(x = data, y = mov_avg, fill = cidade_grande), position = position_stack(reverse = TRUE)) +
  scale_x_date(x_lab, date_breaks = "2 week", date_labels = "%d/%m") +
  scale_y_continuous(y_lab, breaks =y_ticks) +
  scale_colour_manual(color_title, values = color_val, aesthetics = "fill") +
  ggtitle(title) +
  theme(legend.position = "bottom")
ggplot <- ggplotly(plot) %>% 
  layout(legend = list(orientation = "h", 
                       x = 0.3, 
                       y =- 0.25,
                       title = list(text = "Cidades \t")))
```

```{r}
ggplot(temp %>% filter(estado == "RJ")) +
  geom_area(aes(x = data, y = mov_avg, fill = cidade_grande), position = position_stack(reverse = TRUE)) +
  scale_x_date(x_lab, date_breaks = "2 week", date_labels = "%d/%m") +
  scale_y_continuous(y_lab, breaks =y_ticks) +
  scale_colour_manual(color_title, values = color_val, aesthetics = "fill") +
  ggtitle(title) +
  theme(legend.position = "bottom")
ggplot <- ggplotly(plot) %>% 
  layout(legend = list(orientation = "h", 
                       x = 0.3, 
                       y =- 0.25,
                       title = list(text = "Cidades \t")))
```

```{r}
ggplot(temp %>% filter(estado == "MG")) +
  geom_area(aes(x = data, y = mov_avg, fill = cidade_grande), position = position_stack(reverse = TRUE)) +
  scale_x_date(x_lab, date_breaks = "2 week", date_labels = "%d/%m") +
  scale_y_continuous(y_lab, breaks =y_ticks) +
  scale_colour_manual(color_title, values = color_val, aesthetics = "fill") +
  ggtitle(title) +
  theme(legend.position = "bottom")
ggplot <- ggplotly(plot) %>% 
  layout(legend = list(orientation = "h", 
                       x = 0.3, 
                       y =- 0.25,
                       title = list(text = "Cidades \t")))
```

```{r}
ggplot(temp %>% filter(estado == "PE")) +
  geom_area(aes(x = data, y = mov_avg, fill = cidade_grande), position = position_stack(reverse = TRUE)) +
  scale_x_date(x_lab, date_breaks = "2 week", date_labels = "%d/%m") +
  scale_y_continuous(y_lab, breaks =y_ticks) +
  scale_colour_manual(color_title, values = color_val, aesthetics = "fill") +
  ggtitle(title) +
  theme(legend.position = "bottom")
ggplot <- ggplotly(plot) %>% 
  layout(legend = list(orientation = "h", 
                       x = 0.3, 
                       y =- 0.25,
                       title = list(text = "Cidades \t")))
```

